### PR TITLE
Update Dockerfiles under `docker` folder

### PR DESCRIPTION
**Pull request by a-magdy**
- Updated README.md files
- Fixed paths and Dockerfile for docker/plugin
- Updated build.sh scripts with a configurable source code path: `MONSTACHE_SOURCE_CODE_PATH`
- Update root Dockerfile to use `make release` instead of the custom `go build ...` command

### CODE REVIEW

**Comment by rwynn** [comment]
Hi @a-magdy, for the plugin build I wanted it to issue the `go build` command from the plugin directory and not from the root because otherwise go build picks up the main package in monstache.go and builds/downloads dependencies for monstache also.  

My intention with the way things were before was that the plugin source code goes into the plugin directory, go build runs in that directory, and only the plugin itself and its dependencies are built.  Does that make sense?

**Comment by a-magdy** [comment]
Oh, I didn't know that, could you please send me a plugin to test it, I am not sure what would the result be, thanks :)

**Comment by rwynn** [comment]
Hi @a-magdy, there's an example plugin in the docs at https://rwynn.github.io/monstache-site/advanced/#golang.  The main thing I was concerned about was the resulting size and correctness of the resulting .so file.  I had set it up so that the `go build` command would run the sub-directory so that it only picks up the plugin and not the `monstache.go` source code in the root folder.  I think the resulting plugin .so should only be built against the depends and source of the plugin itself.

**Comment by a-magdy** [comment]
The idea of the cache image is to speed up the `go get` command not to get rid of it 

Removing this line will work for now, but if we added another package in the future (maybe in another branch to test another feature) the build will not work

As we already caching all/most of the packages, `go get` will run quickly and it'll confirm that all imported packages are there, add missing packages -if any-

It is a small cost to make sure that the build will always run (now and in other cases)

**Comment by rwynn** [comment]
That makes sense. I’ve been updating the cache image, now on v1.0.2, but I didn’t think of others trying to add new imports in a PR. Let’s keep the line.

**Comment by a-magdy** [comment]
By `Let's keep the line` do you mean:
follow what you did (remove `go get ..` command)
or actually keep the line `go get ..`

**Comment by rwynn** [comment]
I meant let’s keep the go get.  You convinced me.

**Comment by a-magdy** [comment]
Cool, please tell me if I can do anything to move the PR forward :)

**Pull request merged**
