### PR TITLE
added support for UUIDs of mongodb docs IDs which are usually ObjecId…

### PR DESCRIPTION
**Pull request by enterpinamullah**
…. You have to call the global function stringFromBinData in the js script and pass it doc['_id']

### CODE REVIEW

**Comment by rwynn** [comment]
@enterpinamullah thanks for submitting this PR.  

Request: can you also add the same function to the `loadFilters` and `loadPipelines` javascript env?  I think then we can merge it.

**Comment by rwynn** [comment]
So just setting it on the env in those other 2.
```golang
			if err := env.VM.Set("stringFromBinData", jsStringFromBinData); err != nil {
				errorLog.Fatalln(err)
			}
```

**Comment by enterpinamullah** [comment]
Sureeeee sir, i will do that!

**Comment by enterpinamullah** [comment]
No worries, I will do that.

**Comment by enterpinamullah** [comment]
Hi Ryan, its done!

**Pull request merged**
